# spring configuration
spring:
    application:
        name: mysite
    
    devtools:
        restart:
            enable: true
        livereload:
            enable: true
    
    # whether bean definition overriding        
    main:
        allow-bean-definition-overriding: true
        
    #aop
    aop:
        auto: true
        proxy-target-class: true
    
    #mvc
    mvc:
        static-path-pattern: /assets/**
        
    web:
       resources:
          static-locations: [classpath:assets/, file:/mysite-uploads/]
    
    servlet:
        multipart:
            enabled: true
            max-file-size: 10485760
            max-request-size: 104857600
            file-size-threshold: 5242880
        
    # message resources(i18n)
    messages:
          basename: messages/message
          encoding: utf-8
          
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://192.168.0.123:3306/webdb
        username: webdb
        password: webdb
        hikari:
            minimum-idle: 10
            maximum-pool-size: 20                          
       
# mybatis
mybatis:
    config-location: classpath:mybatis/configuration.xml
            
# server configuration
server:
    port: 8080
    servlet:
        context-path: /mysite07
        
# logging
logging:
    config: classpath:logback.xml  